# Generated by Django 4.1.6 on 2023-02-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
